/*
 * JNumberTools Library v3.0.1
 * Copyright (c) 2025 Deepesh Patel (patel.deepesh@gmail.com)
 */
package io.github.deepeshpatel.jnumbertools.generator.base;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;

/**
 * An abstract base class for generators that produce collections of elements.
 * <p>
 * This class provides common functionality for generators that produce combinations,
 * permutations, and other collections of elements. Concrete generator implementations
 * should extend this class.
 * </p>
 *
 * <p>
 * Features provided by this class include:
 * </p>
 * <ul>
 *     <li><strong>Element Retrieval:</strong> Converts indices to their corresponding values.</li>
 *     <li><strong>Stream Support:</strong> Provides a stream view of the generated collections.</li>
 *     <li><strong>Empty Iterator:</strong> Supplies an iterator for an empty collection (mimicking the empty-set(∅)).</li>
 * </ul>
 *
 * @param <E> the type of elements generated by this class
 * @author Deepesh Patel
 */
public abstract class AbstractGenerator<E> implements StreamableIterable<E> {

    /**
     * The list of elements used by this generator.
     * <p>
     * This list is initialized during construction. If {@code null} is provided,
     * it is replaced with an empty list.
     * </p>
     */
    protected final List<E> elements;

    /**
     * Constructs a new {@code AbstractGenerator} with the specified list of elements.
     *
     * @param elements the list of elements to use in the generator; if {@code null},
     *                 an empty list is used
     */
    protected AbstractGenerator(List<E> elements) {
        this.elements = elements;
    }

    /**
     * Converts an array of indices to their corresponding values from the element list.
     *
     * @param indices the array of indices to convert
     * @return an immutable list of values corresponding to the provided indices
     */
    protected final List<E> indicesToValues(int[] indices) {
        var output = new ArrayList<E>(indices.length);
        for (int index : indices) {
            output.add(elements.get(index));
        }
        return List.copyOf(output);
    }

    /**
     * Provides a sequential {@link Stream} with the generated collections as its source.
     *
     * @return a {@link Stream} of lists representing the generated collections
     */
    public Stream<List<E>> stream() {
        return StreamSupport.stream(this.spliterator(), false);
    }
}
