package io.github.deepeshpatel.jnumbertools.generator.base;

/**
 * Interface for building generators of permutations, combinations, and other combinatorial structures.
 * @param <E> The type of elements to generate.
 */
public interface Builder<E> {

    /**
     * Creates a generator that produces elements in lexicographical order.
     *
     * @return An {@link AbstractGenerator} that generates elements in lexicographical order.
     */
    AbstractGenerator<E> lexOrder();

    /**
     * Creates a generator that produces every mth element in lexicographical order, starting from a specified index.
     *
     * @param m The interval of elements to generate.
     * @param start The starting index for generating elements.
     * @return A {@link MthElementGenerator} that generates every mth element in lexicographical order starting from {@code start}.
     */
    MthElementGenerator<E> lexOrderMth(long m, long start);

    /**
     * Returns the total number of elements that can be generated by this builder.
     *
     * @return The count of elements.
     */
    long count();

}
