/*
 * JNumberTools Library v3.0.1
 * Copyright (c) 2025 Deepesh Patel (patel.deepesh@gmail.com)
 */
package io.github.deepeshpatel.jnumbertools.generator.product.simple;

import io.github.deepeshpatel.jnumbertools.generator.base.*;
import io.github.deepeshpatel.jnumbertools.generator.numbers.BigIntegerChoice;
import io.github.deepeshpatel.jnumbertools.generator.numbers.BigIntegerSample;
import io.github.deepeshpatel.jnumbertools.generator.product.CartesianProductByRanks;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;

/**
 * A builder for constructing simple Cartesian products of input lists.
 * <p>
 * This class allows the creation of Cartesian products by combining elements from multiple input lists.
 * Each input list represents a set of elements, and the Cartesian product is generated by selecting
 * one element from each list. The final product can be generated in lexicographical order
 * (via {@link #lexOrder()}), at specific intervals (via {@link #lexOrderMth(BigInteger, BigInteger)}),
 * based on a custom sequence of ranks (via {@link #byRanks(Iterable)}), or sampled randomly with
 * or without replacement (via {@link #choice(int)} and {@link #sample(int)}).
 * </p>
 * <p>
 * This builder is immutable and thread-safe. It can be safely shared across threads
 * without synchronization. The {@code and()} methods return new instances rather than
 * modifying the current instance.
 * </p>
 * <p>
 * Implements {@link Builder} to support composition in complex combinatorial structures,
 * such as nested products or filtered generators. Uses {@code Object} to handle mixed element types.
 * </p>
 *
 * @author Deepesh Patel
 */
@SuppressWarnings({"unchecked"})
public final class SimpleProductBuilder implements Builder<Object> {

    private final List<Builder<Object>> builders;
    private final List<List<?>> allLists;

    /**
     * Constructs a SimpleProductBuilder with an initial list of elements.
     * @param elements   the initial list of elements (null and empty allowed)
     */
    public SimpleProductBuilder(List<?> elements) {
        elements = elements == null ? Collections.emptyList() : elements;
        this.allLists = new ArrayList<>();
        this.builders = new ArrayList<>();
        this.allLists.add(elements);
        this.builders.add(new SingleListBuilder(elements));
    }

    /**
     * Private constructor for creating new instances with existing data.
     */
    private SimpleProductBuilder() {
        this.allLists = new ArrayList<>();
        this.builders = new ArrayList<>();
    }

    /**
     * Adds a new list of elements to the product.
     *
     * @param elements the list of elements to add (null and empty allowed)
     * @return a new instance of SimpleProductBuilder with the additional elements
     */
    public SimpleProductBuilder and(List<?> elements) {
        elements = elements == null ? Collections.emptyList() : elements;
        SimpleProductBuilder newBuilder = new SimpleProductBuilder();
        newBuilder.allLists.addAll(this.allLists);
        newBuilder.builders.addAll(this.builders);
        newBuilder.allLists.add(elements);
        newBuilder.builders.add(new SingleListBuilder(elements));
        return newBuilder;
    }

    /**
     * Adds a new list of elements to the product from a varargs array.
     *
     * @param elements the elements to add
     * @return a new instance of SimpleProductBuilder with the additional elements
     */
    public SimpleProductBuilder and(Object... elements) {
        return and(List.of(elements));
    }

    /**
     * Builds and returns a generator for all products in lexicographical order.
     *
     * @return a StreamableIterable containing all the generated products
     */
    @Override
    public StreamableIterable<Object> lexOrder() {
        return new SimpleProductGenerator();
    }

    /**
     * Builds and returns a generator for every mᵗʰ product in lexicographical order.
     *
     * @param m     the interval to select every mᵗʰ product
     * @param start the starting rank
     * @return a StreamableIterable for the specified intervals
     */
    @Override
    public StreamableIterable<Object> lexOrderMth(BigInteger m, BigInteger start) {
        EveryMthIterable.validateLexOrderMthParams(m, start);
        BigInteger maxCount = count();
        return new StreamableIteratorImpl<>(new CartesianProductByRanks<>(builders, new EveryMthIterable(start, m, maxCount)).iterator());
    }

    /**
     * Generates Cartesian product tuples at specified rank positions.
     * <p>
     * Ranks follow row-major order (rightmost indices vary fastest).
     * </p>
     * <p>
     * <b>Example for [A,B] × [1,2] × [X,Y]:</b>
     * <pre>
     * Rank | Tuple   | Mixed-Radix Digits
     * -----|---------|--------------------
     * 0    | [A,1,X] | [0,0,0]
     * 1    | [A,1,Y] | [0,0,1]
     * 2    | [A,2,X] | [0,1,0]
     * 3    | [A,2,Y] | [0,1,1]
     * 4    | [B,1,X] | [1,0,0]
     * 5    | [B,1,Y] | [1,0,1]
     * 6    | [B,2,X] | [1,1,0]
     * 7    | [B,2,Y] | [1,1,1]
     *
     * byRanks([0, 7]) → [A,1,X], [B,2,Y]
     * </pre>
     *
     * @param ranks Iterable of 0-based rank numbers (0 ≤ rank < product of set sizes)
     * @return a StreamableIterable for the specified ranks
     * @throws IllegalArgumentException if any rank exceeds product space
     * @throws IllegalStateException if no sets were added
     */
    @Override
    public StreamableIterable<Object> byRanks(Iterable<BigInteger> ranks) {
        EveryMthIterable.validateByRanksParams(ranks);
        return new StreamableIteratorImpl<>(new CartesianProductByRanks<>(builders, ranks).iterator());
    }

    /**
     * Generates a random sample of products with replacement.
     *
     * @param sampleSize the number of products to generate
     * @return a StreamableIterable for the sampled products
     * @throws IllegalArgumentException if sampleSize is negative
     */
    public StreamableIterable<Object> choice(int sampleSize) {
        if (sampleSize < 0) {
            throw new IllegalArgumentException("Sample size cannot be negative");
        }
        BigInteger maxCount = count();
        return new StreamableIteratorImpl<>(new CartesianProductByRanks<>(builders, new BigIntegerChoice(maxCount, sampleSize)).iterator());
    }

    /**
     * Generates a random sample of unique products.
     *
     * @param sampleSize the number of unique products to generate
     * @return a StreamableIterable for the sampled products
     * @throws IllegalArgumentException if sampleSize is negative or exceeds total products
     */
    public StreamableIterable<Object> sample(int sampleSize) {
        if (sampleSize < 0) {
            throw new IllegalArgumentException("Sample size cannot be negative");
        }
        BigInteger maxCount = count();
        return new StreamableIteratorImpl<>(new CartesianProductByRanks<>(builders, new BigIntegerSample(maxCount, sampleSize)).iterator());
    }

    /**
     * Returns the total number of possible products.
     *
     * @return the count of products as a BigInteger
     */
    @Override
    public BigInteger count() {
        if (allLists.isEmpty() || allLists.stream().allMatch(List::isEmpty)) {
            return BigInteger.ONE;
        }
        return allLists.stream()
                .map(list -> BigInteger.valueOf(list.size()))
                .reduce(BigInteger.ONE, BigInteger::multiply);
    }

    @Override
    public String toString() {
        return "SimpleProductBuilder{" +
                "allLists=" + allLists +
                ", count=" + count() +
                '}';
    }

    /**
     * A generator for simple products, extending AbstractGenerator.
     */
    private class SimpleProductGenerator extends AbstractGenerator<Object> {
        SimpleProductGenerator() {
            super(Collections.emptyList());
        }

        @Override
        public Iterator<List<Object>> iterator() {
            List<List<Object>> lists = new ArrayList<>();
            for (List<?> list : allLists) {
                lists.add((List<Object>) list);
            }
            return new SimpleProduct(lists).iterator();
        }
    }

    /**
     * A builder that wraps a single list as a set of single-element combinations.
    */
    private record SingleListBuilder(List<?> elements) implements Builder<Object> {
        private SingleListBuilder(List<?> elements) {
            this.elements = elements != null ? elements : Collections.emptyList();
        }

        @Override
        public BigInteger count() {
            return BigInteger.valueOf(elements.size());
        }

        @Override
        public StreamableIterable<Object> lexOrder() {
            return new AbstractGenerator<>(Collections.emptyList()) {
                @Override
                public Iterator<List<Object>> iterator() {
                    List<List<Object>> result = new ArrayList<>();
                    for (Object e : elements) {
                        result.add(List.of(e));
                    }
                    return result.iterator();
                }
            };
        }

        @Override
        public StreamableIterable<Object> lexOrderMth(BigInteger m, BigInteger start) {
            return new StreamableIteratorImpl<>(new Iterator<>() {
                private final Iterator<BigInteger> indexIterator =
                        new EveryMthIterable(start, m, BigInteger.valueOf(elements.size())).iterator();

                @Override
                public boolean hasNext() {
                    return indexIterator.hasNext();
                }

                @Override
                public List<Object> next() {
                    BigInteger index = indexIterator.next();
                    return List.of(elements.get(index.intValue()));
                }
            });
        }

        @Override
        public StreamableIterable<Object> byRanks(Iterable<BigInteger> ranks) {
            return new StreamableIteratorImpl<>(new Iterator<>() {
                private final Iterator<BigInteger> rankIterator = ranks.iterator();

                @Override
                public boolean hasNext() {
                    return rankIterator.hasNext();
                }

                @Override
                public List<Object> next() {
                    BigInteger index = rankIterator.next();
                    return List.of(elements.get(index.intValue()));
                }
            });
        }

        @Override
        public StreamableIterable<Object> choice(int sampleSize) {
            return null;
        }

        @Override
        public StreamableIterable<Object> sample(int sampleSize) {
            return null;
        }
    }
}